name: Sanity End-to-end tests
on: push
jobs:
  HomePage-Verification-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 
          command: npm run test:HomepgaeVerification

  Login-Test-run:
    runs-on: ubuntu-22.04
    steps:
       - name: Checkout
         uses: actions/checkout@v4
        # Install npm dependencies, cache them correctly
        # and run all Cypress tests
       - name: LoginTest run
         uses: cypress-io/github-action@v6
         with: 
            command: npm run test:LoginTest

  
